# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pr: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: inputName
    displayName: What is your name ?
    type: string

steps:
  - script: echo ${{parameters.inputName}} "successfully triggered this build from a REST API Call"
    displayName: "print message from automatically invoked pipeline"
